"""empty message

Revision ID: 327a9a2947b5
Revises: 5e42f0eee440
Create Date: 2026-01-14 07:21:30.725701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327a9a2947b5'
down_revision = '5e42f0eee440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
