"""empty message

Revision ID: 5e42f0eee440
Revises: e6c55e6ddc26
Create Date: 2025-10-23 11:37:18.942300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e42f0eee440'
down_revision = 'e6c55e6ddc26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_progress')
    with op.batch_alter_table('course_lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_content', sa.Text(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('lesson_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=12),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_course_lesson_lesson_type'))
        batch_op.drop_column('content')

    with op.batch_alter_table('course_module', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('course_test', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)

    with op.batch_alter_table('test_option', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('option_text',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('test_question', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('question_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('test_option', schema=None) as batch_op:
        batch_op.alter_column('option_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('course_test', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('course_module', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('course_lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_course_lesson_lesson_type'), ['lesson_type'], unique=False)
        batch_op.alter_column('lesson_type',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('html_content')

    op.create_table('student_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('flag_ok', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('flag_submitted', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['post.id'], name=op.f('student_progress_course_id_fkey')),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lesson.id'], name=op.f('student_progress_lesson_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('student_progress_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_progress_pkey'))
    )
    # ### end Alembic commands ###
