"""empty message

Revision ID: 63577b2a6090
Revises: 7b236c56d55e
Create Date: 2025-08-10 12:50:36.453238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63577b2a6090'
down_revision = '7b236c56d55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
