"""empty message

Revision ID: 714189ee58df
Revises: 09fc7ea5f07c
Create Date: 2025-10-19 21:55:15.762268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714189ee58df'
down_revision = '09fc7ea5f07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sandbox_slug', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_lesson', schema=None) as batch_op:
        batch_op.drop_column('sandbox_slug')

    # ### end Alembic commands ###
