"""empty message

Revision ID: 735a67d033f9
Revises: fa8089da26de
Create Date: 2025-10-17 10:19:55.077375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735a67d033f9'
down_revision = 'fa8089da26de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_login'), ['login'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_login'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    # ### end Alembic commands ###
