"""empty message

Revision ID: 7b236c56d55e
Revises: 
Create Date: 2025-08-10 12:18:34.014770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b236c56d55e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=350), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('srok')
        batch_op.drop_column('predmet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predmet', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('srok', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('bio')
        batch_op.drop_column('subject')
        batch_op.drop_column('exp')

    # ### end Alembic commands ###
