"""empty message

Revision ID: 964efb7fce40
Revises: dcefebfd71b1
Create Date: 2025-08-21 14:02:08.227378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964efb7fce40'
down_revision = 'dcefebfd71b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_course',
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['post.id'], name=op.f('teacher_course_course_id_fkey')),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], name=op.f('teacher_course_teacher_id_fkey')),
    sa.PrimaryKeyConstraint('teacher_id', 'course_id', name=op.f('teacher_course_pkey'))
    )
    # ### end Alembic commands ###
