"""empty message

Revision ID: dcefebfd71b1
Revises: 1fe3703647b7
Create Date: 2025-08-14 12:43:52.922301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dcefebfd71b1'
down_revision = '1fe3703647b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('bio', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('exp', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('level', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('price', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('photo', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('tag', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('student')
        batch_op.drop_column('date')
        batch_op.drop_column('subject')
        batch_op.drop_column('teacher')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('tag')
        batch_op.drop_column('photo')
        batch_op.drop_column('price')
        batch_op.drop_column('level')
        batch_op.drop_column('exp')
        batch_op.drop_column('bio')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
