"""empty message

Revision ID: e6c55e6ddc26
Revises: 714189ee58df
Create Date: 2025-10-20 19:35:50.660218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6c55e6ddc26'
down_revision = '714189ee58df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_lesson', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_course_lesson_lesson_type'), ['lesson_type'], unique=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('course_module', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('course_test', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['lesson_id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_ok', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('flag_submitted', sa.String(length=255), nullable=True))
        batch_op.alter_column('score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('test_option', schema=None) as batch_op:
        batch_op.alter_column('option_text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('test_question', schema=None) as batch_op:
        batch_op.alter_column('question_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_question', schema=None) as batch_op:
        batch_op.alter_column('question_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('test_option', schema=None) as batch_op:
        batch_op.alter_column('option_text',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('score',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.drop_column('flag_submitted')
        batch_op.drop_column('flag_ok')

    with op.batch_alter_table('course_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('course_module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('course_lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_course_lesson_lesson_type'))
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
