"""empty message

Revision ID: fa8089da26de
Revises: 964efb7fce40
Create Date: 2025-09-03 19:18:28.271644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa8089da26de'
down_revision = '964efb7fce40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_lesson')
    op.drop_table('student_progress')
    op.drop_table('course_test')
    op.drop_table('test_question')
    op.drop_table('test_option')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_option',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['test_question.id'], name=op.f('test_option_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_option_pkey'))
    )
    op.create_table('test_question',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['course_test.id'], name=op.f('test_question_test_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_question_pkey'))
    )
    op.create_table('course_test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lesson.id'], name=op.f('course_test_lesson_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('course_test_pkey'))
    )
    op.create_table('student_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['post.id'], name=op.f('student_progress_course_id_fkey')),
    sa.ForeignKeyConstraint(['lesson_id'], ['course_lesson.id'], name=op.f('student_progress_lesson_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('student_progress_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_progress_pkey'))
    )
    op.create_table('course_lesson',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['course_module.id'], name=op.f('course_lesson_module_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('course_lesson_pkey'))
    )
    # ### end Alembic commands ###
